export const WebSocketMessageType = {
  IDENTIFY: 'IDENTIFY',
  START: 'START',
  MOVE: 'MOVE',
  DRAW: 'DRAW',
  SKIP: 'SKIP',
  WIN: 'WIN',
  PING: 'PING',
  GAME_REQUEST: 'GAME_REQUEST',
  GAME_REQUEST_ACCEPTED: 'GAME_REQUEST_ACCEPTED',
  GAME_REQUEST_DECLINED: 'GAME_REQUEST_DECLINED',
  ONLINE_USERS: 'ONLINE_USERS',
  PLAY_WITH_BOT: 'PLAY_WITH_BOT',
  TRANSACTION_FAILED:'TRANSACTION_FAILED',
  TRANSACTION_COMPLETED:'TRANSACTION_COMPLETED'
};
